version: '2'

# For full config, see also docker-compose.{override,prod}.yml

volumes:
  client:
  pgdata:

services:
  nginx:
    image: nginx:stable
    links:
      - hugo
      - kansa
    volumes:
      - ./nginx/conf.template:/nginx.conf.template:ro
      - client:/usr/share/nginx/html/client:ro
    command: /bin/bash -c "envsubst '$$API_SERVER_NAME $$API_SSL_CERTIFICATE $$API_SSL_CERTIFICATE_KEY' < /nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  client-build:
    build: ./client
    environment:
      NODE_ENV: production
    volumes:
      - client:/usr/src/app/dist

  hugo:
    build: ./hugo/server
    entrypoint: ./wait-for-it.sh postgres:5432 -- npm start
    links:
      - postgres
    expose:
      - "3000"

  kansa:
    build: ./kansa/server
    entrypoint: ./wait-for-it.sh postgres:5432 -- npm start
    links:
      - kyyhky
      - postgres
    expose:
      - "3000"

  kyyhky:
    build: ./kyyhky
    entrypoint: ./wait-for-it.sh redis:6379 -- npm start
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    links:
      - redis
    expose:
      - "3000"

  redis:
    image: redis:3.2
    expose:
      - "6379"

  postgres:
    build: ./postgres
    environment:
      PGDATA: /pgdata
      PGUSER: admin
      POSTGRES_DB: api
      POSTGRES_USER: admin
    expose:
      - "5432"
    volumes:
      - pgdata:/pgdata

  postgres-replica:
    image: danieldent/postgres-replication:9.5
    environment:
      PGDATA: /pgdata
      PGUSER: admin
      POSTGRES_DB: api
      POSTGRES_USER: admin
      REPLICATE_FROM: postgres
    expose:
      - "5432"
    volumes:
      - /pgdata
    links:
      - postgres
