version: '2'

# docker-compose base layer
#
# This config is not sufficient by itself; it's just the base layer.
# For full config, see also docker-compose.{dev,prod}.yaml

volumes:
  pgdata: null

services:
  nginx:
    build: ../nginx
    links:
      - hugo
      - kansa
      - raami
    entrypoint: /bin/bash -c "envsubst '$$SERVER_NAME $$SSL_CERTIFICATE $$SSL_CERTIFICATE_KEY' < /nginx.conf.template > /usr/local/openresty/nginx/conf/nginx.conf && /usr/local/openresty/bin/openresty -g 'daemon off;'"

  hugo:
    build: ../hugo
    entrypoint: ./wait-for-it.sh postgres:5432 -- npm start
    links:
      - postgres
    expose:
      - '80'
    volumes:
      - ../config/kansa.yaml:/kansa.yaml:ro

  kansa:
    build: ../kansa
    entrypoint: ./wait-for-it.sh postgres:5432 -- npm start
    links:
      - kyyhky
      - postgres
      - tarra
      - tuohi
    expose:
      - '80'
    volumes:
      - ../config/kansa.yaml:/kansa.yaml:ro
      - ../config/siteselection/ballot-data.js:/ss-ballot-data.js:ro

  raami:
    build: ../raami
    entrypoint: ./wait-for-it.sh postgres:5432 -- npm start
    links:
      - postgres
    expose:
      - '3000'
    volumes:
      - ../config/kansa.yaml:/kansa.yaml:ro

  tarra:
    image: worldcon75devops/label-printer:0.3.0
    expose:
      - '80'

  tuohi:
    image: eeemeli/pdf-form-fill:0.2
    expose:
      - '3000'
    environment:
      PDF_TEMPLATE_DIR: /templates
    volumes:
      - ../config/siteselection/ballot.pdf:/templates/ss-ballot.pdf:ro

  kyyhky:
    build: ../kyyhky
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    links:
      - redis
    expose:
      - '80'
    volumes:
      - ../config/message-templates:/message-templates:ro

  redis:
    image: redis:4.0
    expose:
      - '6379'

  postgres:
    image: postgres:10.4
    environment:
      PGDATA: /pgdata
      PGUSER: admin
      POSTGRES_DB: api
      POSTGRES_USER: admin
    expose:
      - '5432'
    volumes:
      - pgdata:/pgdata
      - ../postgres/init/10-admin-init.sql:/docker-entrypoint-initdb.d/10-admin-init.sql:ro
      - ../postgres/init/20-kansa-init.sql:/docker-entrypoint-initdb.d/20-kansa-init.sql:ro
      - ../postgres/init/22-kansa-tables.sql:/docker-entrypoint-initdb.d/22-kansa-tables.sql:ro
      - ../postgres/init/25-day-passes.sql:/docker-entrypoint-initdb.d/25-day-passes.sql:ro
      - ../postgres/init/25-payments.sql:/docker-entrypoint-initdb.d/25-payments.sql:ro
      - ../postgres/init/25-public-data.sql:/docker-entrypoint-initdb.d/25-public-data.sql:ro
      - ../postgres/init/28-siteselection.sql:/docker-entrypoint-initdb.d/28-siteselection.sql:ro
      - ../config/database/membership-types.sql:/docker-entrypoint-initdb.d/29-membership-types.sql:ro
      - ../postgres/init/30-hugo-init.sql:/docker-entrypoint-initdb.d/30-hugo-init.sql:ro
      - ../config/database/31-hugo-categories.sql:/docker-entrypoint-initdb.d/31-hugo-categories.sql:ro
      - ../postgres/init/32-hugo-tables.sql:/docker-entrypoint-initdb.d/32-hugo-tables.sql:ro
      - ../postgres/init/40-raami-init.sql:/docker-entrypoint-initdb.d/40-raami-init.sql:ro
